image: 'nimlang/choosenim'

before_script:
  - choosenim update self
  - choosenim update devel
  - nimble install -d -Y

pages:
  script:
    - nim doc --project --git.commit:master --git.devel:master --git.url:https://gitlab.com/tandy1000/lastfm-nim --outdir:public src/lastfm.nim
    - rm --verbose public/lastfm/*.idx
    - rm --verbose --force --recursive public/nimcache/*.*
    - mv --verbose public/lastfm.html public/index.html
  artifacts:
    paths:
      - public

test:
  script:
    - echo 'tzdata tzdata/Areas select Europe' | debconf-set-selections
    - echo 'tzdata tzdata/Zones/Europe select Paris' | debconf-set-selections
    - apt-get -qq update
    - DEBIAN_FRONTEND="noninteractive" apt install -y tzdata
    - apt-get -qq install -y make autoconf gcc g++ gcovr lcov
    - nimble install -Y coco
    - coco --target "tests/test.nim" --cov '!tests' --compiler="--hints:off" 
    - lcov --remove lcov.info "*.nim.c" -o lcov.info 
    - lcov --list lcov.info
